In [1]:
import requests 
from bs4 import BeautifulSoup as bs
import pandas as pd
import tldextract
import numpy as np
import matplotlib.pylab as plt
import os
import re

In [2]:
def on_sale_chk(text):
    if len(text)<1:
        return False
    return 'domain' in text and 'sale' in text

def on_parked_chk(text):
    if len(text)<1:
        return True
    return 'domain' in text and 'park' in text

def on_Parked(text):
    if len(text)<1:
        return True
    return (('website' in text or 'content' in text) and 'unavailable' in text) or ('will' in text and 'soon' in text)

In [3]:
#returns status code, parked or on sale

def soupFromUrl(scrapeUrl):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; zh-CN) AppleWebKit/533+ (KHTML, like Gecko)'}
    try:
        req = requests.get(scrapeUrl, headers=headers, timeout=5)
        # print(req.status_code)
        req.close()
        if req.status_code == 200:
            # print(bs(req.text, 'html.parser').get_text().strip().replace('\n',' '))
            soup = bs(req.text,'lxml')

            # print(soup)

            text = ''

            if soup.body:
                text = re.sub(r'[^\w]', ' ',soup.body.get_text(' ', strip=True).lower())

            # print(soup)

            # print('text',text)
            # print(bs(req.text, 'html.parser'))
            # return [bs(req.text, 'html.parser'),len(req.text), len(req.content), req.status_code]
            # print([len(req.content), len(text), req.status_code, 0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))])
            return [req.status_code,0+(on_sale_chk(text) or on_Parked(text) or on_parked_chk(text))]
        else:
            # return [-1,0,0,req.status_code]
            return [req.status_code,0]
    except:
        # return [-1,0,0,-1]
        return [-1,0]

In [4]:
data = pd.read_csv('../Data/Clusters/All_5_Clustering_Algo_Result_10-30-2024.csv')
data.head()

,Landing_Page_Size_In_KB,Same Landing Domain,Has Bank Related Keywords,Has Crypto Related Keywords,Has Card Related Keywords,Unique_Internal_Page_Link_Cnt,Unique_External_Page_Link_Cnt,Avg_External_Links_Len,Stdv_External_Links_Len,Ratio_Shortened_URL_And_External_Links,...,Hierarchical Label,DBSCAN Label,GMM Label,Majority Voting Label,IPQS_Flag,Domain,TLD,Searched_URL,Status Code,Parked Status
0,86.53,1,0,0,0,7,5,50.80,10.26,0.0,...,0,0,0,0,0,1001minutesforukraine.com,com,https://www.1001minutesforukraine.com,200,0
1,123.73,1,0,0,0,15,2,75.50,32.50,0.0,...,0,0,0,0,0,1to1ukrainemuseums.org,org,https://www.1to1ukrainemuseums.org,200,1
2,96.91,1,0,0,0,2,3,43.00,5.10,0.0,...,0,0,0,0,0,1violettepourlukraine.fr,fr,https://www.1violettepourlukraine.fr,200,0
3,1170.81,1,0,0,0,1,14,45.43,24.74,0.0,...,0,0,0,0,0,33lettersforukraine.com,com,https://www.33lettersforukraine.com,-1,0
4,47.44,1,0,0,0,25,19,29.11,17.09,0.0,...,2,0,2,2,1,4myukraine.com,com,https://www.4myukraine.com,-1,0

In [5]:
# data = data.drop(columns='Unnamed: 0', axis=1)

In [6]:
data['Status Code'].value_counts()

Status Code
 200    1617
-1       420
 404      47
 403      13
 503       4
 500       4
 520       3
 401       2
 530       2
 521       2
 502       1
 418       1
 429       1
 423       1
Name: count, dtype: int64

In [7]:
# new_status_code = []
# parked_status = []

# for idx,i in enumerate(data['Searched_URL']):
#     res = soupFromUrl(i)

#     new_status_code.append(res[0])
#     parked_status.append(res[1])
#     # break

In [8]:
# len(parked_status)

In [9]:
# print(new_status_code)
# print(parked_status)

In [10]:
# new_status_code.count(200)

In [11]:
# data['Status Code'] = new_status_code
# data['Parked Status'] = parked_status

In [18]:
data['Parked Status'].value_counts()

Parked Status
0    1833
1     285
Name: count, dtype: int64

In [12]:
print(len(data[(data['Majority Voting Label']==0) & (data['Parked Status']==1)]))
print(len(data[(data['Majority Voting Label']==1) & (data['Parked Status']==1)]))
print(len(data[(data['Majority Voting Label']==2) & (data['Parked Status']==1)]))

105
127
53

In [13]:
print(len(data[(data['IPQS_Flag']==1) & (data['Parked Status']==1)])/len(data[data['Parked Status']==1]))

0.4807017543859649

In [14]:
data.to_csv('../Data/Clusters/All_5_Clustering_Algo_Result_10-30-2024.csv', index=None)

In [15]:
print(len(data[(data['Majority Voting Label']==0) & (data['Parked Status']==1) & (data['IPQS_Flag']==1)]))
print(len(data[(data['Majority Voting Label']==1) & (data['Parked Status']==1) & (data['IPQS_Flag']==1)]))
print(len(data[(data['Majority Voting Label']==2) & (data['Parked Status']==1) & (data['IPQS_Flag']==1)]))

14
102
21

In [16]:
print(len(data[(data['Parked Status']==1) & (data['IPQS_Flag']==1)]))
print(len(data[(data['Parked Status']==1) & (data['IPQS_Flag']==1)]))
print(len(data[(data['Parked Status']==1) & (data['IPQS_Flag']==1)]))

137
137
137

In [21]:
IPQS_data = pd.read_csv('../Data/2118_IPQS_Analysis_Data.csv')
print(len(IPQS_data))
IPQS_data.head()

2118

,url,unsafe,status_code,parking,spamming,malware,phishing,suspicious,adult,risk_score
0,https://www.napavalleytoukraine.org,False,301,False,False,False,False,False,False,0
1,https://www.cannabiswithukraine.org,False,200,False,False,False,False,True,False,90
2,https://www.givetoukrainetoday.com,False,200,False,False,False,False,True,False,55
3,https://www.beforukraine.com,False,200,True,False,False,False,True,False,90
4,https://www.ukrainekc.org,False,200,False,False,False,False,False,False,0

In [24]:
len(set(IPQS_data['url']).intersection(set(data['Searched_URL'])))

2118

In [27]:
sorted_IPQS_data = data[['Searched_URL']].rename(columns={'Searched_URL': 'url'}).merge(IPQS_data, on='url', how='left')
sorted_IPQS_data.head()

,url,unsafe,status_code,parking,spamming,malware,phishing,suspicious,adult,risk_score
0,https://www.1001minutesforukraine.com,False,200,False,False,False,False,False,False,0
1,https://www.1to1ukrainemuseums.org,False,200,False,False,False,False,True,False,55
2,https://www.1violettepourlukraine.fr,False,200,False,False,False,False,False,False,0
3,https://www.33lettersforukraine.com,False,200,False,False,False,False,True,False,55
4,https://www.4myukraine.com,True,200,False,False,False,True,True,False,91

In [37]:
####Overall####

#was parked in ipqs query
print(len(sorted_IPQS_data[sorted_IPQS_data['parking']==True]))


#was park till last this research
print(len(data[data['Parked Status']==1]))


#was parked when ipqs was queried but got back live again
cnt_x = 0
for i in range(len(data)):
    if IPQS_data['parking'][i]==True and data['Parked Status'][i]==0:
        cnt_x+=1

print(cnt_x) 


#was not parked when ipqs was queried but got parked in the time of this research
cnt_xx = 0
for i in range(len(data)):
    if IPQS_data['parking'][i]==False and data['Parked Status'][i]==1:
        cnt_xx+=1

print(cnt_xx) 



#was parked when ipqs was queried and now also parked in the time of this research
cnt_xxx = 0
for i in range(len(data)):
    if IPQS_data['parking'][i]==True and data['Parked Status'][i]==1:
        cnt_xxx+=1

print(cnt_xxx)

215
285
193
263
22

In [41]:
####Cluster C_1####

#was parked in ipqs query
cnt_y = 0
for i in range(len(data)):
    if data['Majority Voting Label'][i]==0 and sorted_IPQS_data['parking'][i]==True:
        cnt_y+=1
print(cnt_y)


#was park till last this research
print(len(data[(data['Majority Voting Label']==0) & (data['Parked Status']==1)]))




#was parked when ipqs was queried but got back live again
cnt_x = 0
for i in range(len(data)):
    if data['Majority Voting Label'][i]==0 and IPQS_data['parking'][i]==True and data['Parked Status'][i]==0:
        cnt_x+=1

print(cnt_x) 


#was not parked when ipqs was queried but got parked in the time of this research
cnt_xx = 0
for i in range(len(data)):
    if data['Majority Voting Label'][i]==0 and IPQS_data['parking'][i]==False and data['Parked Status'][i]==1:
        cnt_xx+=1

print(cnt_xx) 



#was parked when ipqs was queried and now also parked in the time of this research
cnt_xxx = 0
for i in range(len(data)):
    if data['Majority Voting Label'][i]==0 and IPQS_data['parking'][i]==True and data['Parked Status'][i]==1:
        cnt_xxx+=1

print(cnt_xxx)

30
105
112
96
9

In [43]:
####Cluster C_2####


#was parked in ipqs query
cnt_y = 0
for i in range(len(data)):
    if data['Majority Voting Label'][i]==1 and sorted_IPQS_data['parking'][i]==True:
        cnt_y+=1
print(cnt_y)


#was park till last this research
print(len(data[(data['Majority Voting Label']==1) & (data['Parked Status']==1)]))





#was parked when ipqs was queried but got back live again
cnt_x = 0
for i in range(len(data)):
    if data['Majority Voting Label'][i]==1 and IPQS_data['parking'][i]==True and data['Parked Status'][i]==0:
        cnt_x+=1

print(cnt_x) 


#was not parked when ipqs was queried but got parked in the time of this research
cnt_xx = 0
for i in range(len(data)):
    if data['Majority Voting Label'][i]==1 and IPQS_data['parking'][i]==False and data['Parked Status'][i]==1:
        cnt_xx+=1

print(cnt_xx) 



#was parked when ipqs was queried and now also parked in the time of this research
cnt_xxx = 0
for i in range(len(data)):
    if data['Majority Voting Label'][i]==1 and IPQS_data['parking'][i]==True and data['Parked Status'][i]==1:
        cnt_xxx+=1

print(cnt_xxx)

129
127
28
117
10

In [44]:
####Cluster C_3####



#was parked in ipqs query
cnt_y = 0
for i in range(len(data)):
    if data['Majority Voting Label'][i]==2 and sorted_IPQS_data['parking'][i]==True:
        cnt_y+=1
print(cnt_y)


#was park till last this research
print(len(data[(data['Majority Voting Label']==2) & (data['Parked Status']==1)]))







#was parked when ipqs was queried but got back live again
cnt_x = 0
for i in range(len(data)):
    if data['Majority Voting Label'][i]==2 and IPQS_data['parking'][i]==True and data['Parked Status'][i]==0:
        cnt_x+=1

print(cnt_x) 


#was not parked when ipqs was queried but got parked in the time of this research
cnt_xx = 0
for i in range(len(data)):
    if data['Majority Voting Label'][i]==2 and IPQS_data['parking'][i]==False and data['Parked Status'][i]==1:
        cnt_xx+=1

print(cnt_xx) 



#was parked when ipqs was queried and now also parked in the time of this research
cnt_xxx = 0
for i in range(len(data)):
    if data['Majority Voting Label'][i]==2 and IPQS_data['parking'][i]==True and data['Parked Status'][i]==1:
        cnt_xxx+=1

print(cnt_xxx)

56
53
53
50
3